# Generated by Django 4.2.3 on 2023-07-18 23:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutContent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='about_page_description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
