# Generated by Django 4.2.3 on 2023-07-18 00:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Home_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
