# Generated by Django 4.2.3 on 2023-07-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savehome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=56)),
                ('phone', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=56)),
                ('message', models.CharField(max_length=54)),
            ],
        ),
    ]
