# Generated by Django 4.2.4 on 2023-08-31 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_customer_id_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.CharField(default=django.utils.timezone.now, max_length=50000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='no_of_product_item',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
