# Generated by Django 4.2.4 on 2023-08-31 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_product_price_alter_cart_no_of_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='customer_email',
        ),
    ]
