# Generated by Django 4.2.4 on 2023-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_customer_cart_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_email',
            field=models.CharField(max_length=500),
        ),
    ]
