# Generated by Django 4.2.4 on 2023-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to='cartImages/'),
        ),
    ]
