# Generated by Django 4.2.4 on 2023-09-02 22:28

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.FileField(max_length=5000, upload_to='whitelist_images/')),
                ('customer_email', models.EmailField(max_length=300)),
                ('product_price', models.CharField(max_length=60)),
                ('total_of_product_item', models.CharField(max_length=799)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True)),
            ],
        ),
    ]
