# Generated by Django 4.2.4 on 2023-09-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemwhitelist', '0002_alter_whitelist_total_of_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelist',
            name='total_of_product_item',
        ),
    ]
