# Generated by Django 4.2.4 on 2023-09-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=69)),
                ('country', models.CharField(max_length=54)),
                ('city', models.CharField(max_length=76)),
                ('address', models.CharField(max_length=34)),
                ('login_email', models.EmailField(max_length=76)),
                ('tel', models.CharField(max_length=43)),
                ('mobile', models.CharField(max_length=76)),
                ('ordernote', models.CharField(max_length=76)),
                ('payment', models.CharField(max_length=54)),
                ('product_name', models.CharField(max_length=65)),
                ('no_of_product_item', models.IntegerField()),
                ('product_price', models.CharField(max_length=76)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=34)),
            ],
        ),
    ]
