# Generated by Django 4.2.4 on 2023-09-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekOut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetail',
            name='slug',
            field=models.CharField(default='checkoutall', max_length=34),
        ),
    ]
