# Generated by Django 4.2.4 on 2023-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekOut', '0002_checkoutdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetail',
            name='ordernote',
            field=models.CharField(default='None', max_length=76),
        ),
    ]
