# Generated by Django 4.2.4 on 2023-09-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekOut', '0003_alter_checkoutdetail_ordernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetail',
            name='no_of_product_item',
            field=models.IntegerField(default='0'),
        ),
    ]
