# Generated by Django 4.2.4 on 2023-08-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensCloths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(max_length=8000, upload_to='')),
                ('product_category', models.CharField(default='MensCloths', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_short_description', models.CharField(max_length=100)),
                ('product_long_description', models.CharField(max_length=500)),
                ('product_quantity', models.IntegerField(max_length=100)),
                ('product_total_amount', models.IntegerField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='MensShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(max_length=8000, upload_to='')),
                ('product_category', models.CharField(default='MensShoes', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_short_description', models.CharField(max_length=100)),
                ('product_long_description', models.CharField(max_length=500)),
                ('product_quantity', models.IntegerField(max_length=100)),
                ('product_total_amount', models.IntegerField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='MensWatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(max_length=8000, upload_to='')),
                ('product_category', models.CharField(default='MensWatches', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_short_description', models.CharField(max_length=100)),
                ('product_long_description', models.CharField(max_length=500)),
                ('product_quantity', models.IntegerField(max_length=100)),
                ('product_total_amount', models.IntegerField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='WomensGlasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(max_length=8000, upload_to='')),
                ('product_category', models.CharField(default='MensGlasses', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_short_description', models.CharField(max_length=100)),
                ('product_long_description', models.CharField(max_length=500)),
                ('product_quantity', models.IntegerField(max_length=100)),
                ('product_total_amount', models.IntegerField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='WomensHandbags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(max_length=8000, upload_to='')),
                ('product_category', models.CharField(default='WomensHandbags', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_short_description', models.CharField(max_length=100)),
                ('product_long_description', models.CharField(max_length=500)),
                ('product_quantity', models.IntegerField(max_length=100)),
                ('product_total_amount', models.IntegerField(max_length=9000)),
            ],
        ),
    ]
