# Generated by Django 4.2.4 on 2023-08-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menscloths',
            name='product_image',
            field=models.FileField(max_length=8000, upload_to='MensCloths/'),
        ),
        migrations.AlterField(
            model_name='menscloths',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menscloths',
            name='product_total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mensshoes',
            name='product_image',
            field=models.FileField(max_length=8000, upload_to='MensShoes/'),
        ),
        migrations.AlterField(
            model_name='mensshoes',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mensshoes',
            name='product_total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menswatches',
            name='product_image',
            field=models.FileField(max_length=8000, upload_to='MensWatches/'),
        ),
        migrations.AlterField(
            model_name='menswatches',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menswatches',
            name='product_total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='womensglasses',
            name='product_image',
            field=models.FileField(max_length=8000, upload_to='WomensGlasses'),
        ),
        migrations.AlterField(
            model_name='womensglasses',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='womensglasses',
            name='product_total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='womenshandbags',
            name='product_image',
            field=models.FileField(max_length=8000, upload_to='WomensHandbags/'),
        ),
        migrations.AlterField(
            model_name='womenshandbags',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='womenshandbags',
            name='product_total_amount',
            field=models.IntegerField(),
        ),
    ]
