# Generated by Django 4.2.4 on 2023-08-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_menscloths_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menscloths',
            name='product_total_amount',
        ),
        migrations.RemoveField(
            model_name='mensshoes',
            name='product_total_amount',
        ),
        migrations.RemoveField(
            model_name='menswatches',
            name='product_total_amount',
        ),
        migrations.RemoveField(
            model_name='womensglasses',
            name='product_total_amount',
        ),
        migrations.RemoveField(
            model_name='womenshandbags',
            name='product_total_amount',
        ),
    ]
