# Generated by Django 4.2.4 on 2023-08-30 23:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_menscloths_product_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menscloths',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True),
        ),
        migrations.AddField(
            model_name='mensshoes',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True),
        ),
        migrations.AddField(
            model_name='menswatches',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True),
        ),
        migrations.AddField(
            model_name='womensglasses',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True),
        ),
        migrations.AddField(
            model_name='womenshandbags',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True),
        ),
    ]
