# Generated by Django 4.2.4 on 2023-08-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='description',
        ),
    ]
