# Generated by Django 4.2.4 on 2023-08-30 23:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_rename_content_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
